#!/usr/bin/env python3
"""Kconfig front end for zuzu.

    kconf.py <command> --config <.config> [--defconfig <file>] [--out <dir>]

Commands:
    defconfig     write .config from the board defconfig (discards changes)
    olddefconfig  keep .config, fill in anything new with its default
    menuconfig    interactive editor
    savedefconfig write the minimal form of .config back to the defconfig
    sync          regenerate autoconf.h + auto.conf from .config

Generated files are only rewritten when their contents change, so a no-op
menuconfig does not make every object look out of date.
"""

import argparse
import os
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent / "vendor" / "kconfiglib"))

import kconfiglib  # noqa: E402


def write_if_changed(path, text):
    p = pathlib.Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    if p.exists() and p.read_text() == text:
        return False
    p.write_text(text)
    return True


def render_autoconf(kconf):
    out = ["/* Generated by scripts/kconf.py -- do not edit. */",
           "#ifndef ZUZU_AUTOCONF_H", "#define ZUZU_AUTOCONF_H", ""]
    for sym in kconf.unique_defined_syms:
        name, val = "CONFIG_" + sym.name, sym.str_value
        if sym.type in (kconfiglib.BOOL, kconfiglib.TRISTATE):
            if val == "y":
                out.append(f"#define {name} 1")
        elif sym.type == kconfiglib.STRING:
            out.append(f'#define {name} "{val}"')
        elif sym.type in (kconfiglib.INT, kconfiglib.HEX):
            if val != "":
                prefix = "0x" if sym.type == kconfiglib.HEX else ""
                out.append(f"#define {name} {prefix}{val}")
    out += ["", "#endif /* ZUZU_AUTOCONF_H */", ""]
    return "\n".join(out)


def render_autoconf_mk(kconf):
    # Consumed by make. Only y-valued bools are emitted, so obj-$(CONFIG_X)
    # naturally drops to obj- when X is off.
    out = ["# Generated by scripts/kconf.py -- do not edit.", "CONFIG_ZUZU_VALID = y"]
    for sym in kconf.unique_defined_syms:
        name, val = "CONFIG_" + sym.name, sym.str_value
        if sym.type in (kconfiglib.BOOL, kconfiglib.TRISTATE):
            if val == "y":
                out.append(f"{name} = y")
        elif val != "":
            out.append(f"{name} = {val}")
    out.append("")
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("command", choices=["defconfig", "olddefconfig", "menuconfig",
                                        "savedefconfig", "sync"])
    ap.add_argument("--kconfig", default="Kconfig")
    ap.add_argument("--config", required=True)
    ap.add_argument("--defconfig")
    ap.add_argument("--out", help="directory for autoconf.h / auto.conf")
    args = ap.parse_args()

    # kconfiglib reads this from the environment, and will not create the
    # directory it writes into.
    os.environ["KCONFIG_CONFIG"] = args.config
    pathlib.Path(args.config).parent.mkdir(parents=True, exist_ok=True)
    kconf = kconfiglib.Kconfig(args.kconfig, warn_to_stderr=False)

    if args.command == "defconfig":
        if not args.defconfig or not os.path.exists(args.defconfig):
            print(f"kconf: no defconfig at {args.defconfig}, using Kconfig defaults",
                  file=sys.stderr)
        else:
            kconf.load_config(args.defconfig)
        kconf.write_config(args.config)
    elif args.command == "olddefconfig":
        if os.path.exists(args.config):
            kconf.load_config(args.config)
        elif args.defconfig and os.path.exists(args.defconfig):
            kconf.load_config(args.defconfig)
        kconf.write_config(args.config)
    elif args.command == "menuconfig":
        if os.path.exists(args.config):
            kconf.load_config(args.config)
        elif args.defconfig and os.path.exists(args.defconfig):
            kconf.load_config(args.defconfig)
        import menuconfig
        menuconfig.menuconfig(kconf)
        kconf = kconfiglib.Kconfig(args.kconfig, warn_to_stderr=False)
        kconf.load_config(args.config)
    elif args.command == "savedefconfig":
        kconf.load_config(args.config)
        kconf.write_min_config(args.defconfig)
        print(f"  SAVEDEF {args.defconfig}", file=sys.stderr)
        return
    elif args.command == "sync":
        kconf.load_config(args.config)

    if args.out:
        h = os.path.join(args.out, "autoconf.h")
        mk = os.path.join(args.out, "auto.conf")
        changed = write_if_changed(h, render_autoconf(kconf))
        write_if_changed(mk, render_autoconf_mk(kconf))
        if changed:
            print(f"  CFG     {h}", file=sys.stderr)


if __name__ == "__main__":
    main()
