#!/usr/bin/env python3
"""
ttf_to_bitmap_font.py — Rasterize a TTF into a fixed-size 1-bit bitmap font,
packed as a C header for use as a kernel/userspace glyph table (e.g. fbcons).

This is a one-time HOST-SIDE asset pipeline tool. It does not touch zuzu at
all — it just produces a .h file you #include or embed.

Usage:
    python3 ttf_to_bitmap_font.py --font MyFont.ttf --out font16x16.h

Output format:
    static const uint16_t font16x16[NUM_GLYPHS][16] = { ... };
    Row i of a glyph is one uint16_t. Bit 15 (MSB) = leftmost pixel,
    bit 0 (LSB) = rightmost of the 16 columns. font[ch - FIRST_CHAR] is
    the glyph for ASCII value 'ch'.

Also writes a PNG contact sheet (font16x16_preview.png) tiling every glyph
so you can eyeball the result before ever booting zuzu with it.
"""

import argparse
import sys

from PIL import Image, ImageDraw, ImageFont

CELL = 16          # fixed glyph cell size (matches fbcons's 16x16 font)
FIRST_CHAR = 32    # space
LAST_CHAR = 126    # '~'
THRESHOLD = 128    # grayscale cutoff for 1-bit conversion


def find_render_size(font_path: str, target_px: int) -> int:
    """
    TTF point size != rendered pixel height (depends on font metrics), so we
    binary-search for a point size whose rendered ascent+descent is closest
    to target_px. This keeps glyphs consistently sized across different
    fonts without manual trial and error per font file.
    """
    best_size, best_diff = target_px, 10**9
    for size in range(6, target_px * 3):
        font = ImageFont.truetype(font_path, size)
        ascent, descent = font.getmetrics()
        height = ascent + descent
        diff = abs(height - target_px)
        if diff < best_diff:
            best_diff, best_size = diff, size
        if height > target_px * 2:
            break
    return best_size


def render_glyph(font: ImageFont.FreeTypeFont, ch: str) -> Image.Image:
    """Render one character into a CELLxCELL 8-bit grayscale canvas,
    baseline-aligned so ascenders/descenders sit consistently."""
    canvas = Image.new("L", (CELL, CELL), 0)
    draw = ImageDraw.Draw(canvas)
    ascent, _ = font.getmetrics()
    # Anchor: left edge at x=0, baseline at y=ascent (clamped into the cell).
    baseline_y = min(ascent, CELL - 1)
    draw.text((0, baseline_y - ascent), ch, font=font, fill=255)
    return canvas


def pack_rows(glyph_img: Image.Image) -> list[int]:
    """Threshold to 1-bit and pack each row into a uint16_t.
    Bit 15 = leftmost pixel (column 0), bit 0 = column 15."""
    bw = glyph_img.point(lambda p: 255 if p >= THRESHOLD else 0)
    rows = []
    for y in range(CELL):
        word = 0
        for x in range(CELL):
            if bw.getpixel((x, y)) >= THRESHOLD:
                word |= 1 << (CELL - 1 - x)
        rows.append(word)
    return rows


def build_preview(glyph_imgs: dict[int, Image.Image], cols: int = 16) -> Image.Image:
    """Tile all glyphs into one PNG for visual sanity-checking."""
    n = len(glyph_imgs)
    rows = (n + cols - 1) // cols
    sheet = Image.new("L", (cols * CELL, rows * CELL), 0)
    for i, ch in enumerate(sorted(glyph_imgs)):
        x = (i % cols) * CELL
        y = (i // cols) * CELL
        sheet.paste(glyph_imgs[ch], (x, y))
    # Scale up so it's actually visible when opened.
    return sheet.resize((sheet.width * 4, sheet.height * 4), Image.NEAREST)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--font", required=True, help="Path to .ttf/.otf file")
    ap.add_argument("--out", default="font16x16.h", help="Output C header path")
    ap.add_argument("--array-name", default="font16x16", help="C array identifier")
    ap.add_argument("--preview", default="font16x16_preview.png")
    args = ap.parse_args()

    render_size = find_render_size(args.font, CELL)
    font = ImageFont.truetype(args.font, render_size)
    print(f"[info] rasterizing at point size {render_size} for {CELL}px target height")

    glyph_imgs = {}
    glyph_rows = {}
    for code in range(FIRST_CHAR, LAST_CHAR + 1):
        ch = chr(code)
        img = render_glyph(font, ch)
        glyph_imgs[code] = img
        glyph_rows[code] = pack_rows(img)

    num_glyphs = LAST_CHAR - FIRST_CHAR + 1

    with open(args.out, "w") as f:
        f.write("// Auto-generated by ttf_to_bitmap_font.py — do not edit by hand.\n")
        f.write(f"// Source font: {args.font}\n")
        f.write(f"// {CELL}x{CELL} 1-bit glyphs, ASCII {FIRST_CHAR}..{LAST_CHAR}\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"#define FONT_FIRST_CHAR {FIRST_CHAR}\n")
        f.write(f"#define FONT_LAST_CHAR  {LAST_CHAR}\n")
        f.write(f"#define FONT_GLYPH_W    {CELL}\n")
        f.write(f"#define FONT_GLYPH_H    {CELL}\n\n")
        f.write(f"static const uint16_t {args.array_name}[{num_glyphs}][{CELL}] = {{\n")
        for code in range(FIRST_CHAR, LAST_CHAR + 1):
            rows = glyph_rows[code]
            row_str = ", ".join(f"0x{r:04X}" for r in rows)
            ch_display = chr(code) if code != 32 else "space"
            f.write(f"    {{ {row_str} }}, // {code} '{ch_display}'\n")
        f.write("};\n")

    preview = build_preview(glyph_imgs)
    preview.save(args.preview)

    print(f"[ok] wrote {args.out} ({num_glyphs} glyphs)")
    print(f"[ok] wrote {args.preview} — inspect before using")


if __name__ == "__main__":
    main()